"""Data contracts module for declarative schema and validation rules.

This module provides:
- DataContract and related models for defining data expectations
- YAML loading and validation
- Runtime validators for DataFrames
- Dagster asset check generation
"""

from moncpipelib.contracts.checks import (
    discover_contract_checks,
    generate_asset_check,
    generate_asset_checks_from_contract,
    load_contract_checks,
    make_contract_checks,
)
from moncpipelib.contracts.checks_types import (
    # Column tests (typed)
    AcceptedValues,
    Between,
    # Type aliases
    ColumnTestType,
    # Table expectations (typed)
    Freshness,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    MaxLength,
    MinLength,
    NotIn,
    NotInFuture,
    NotNull,
    NullPercentage,
    Pattern,
    RowCount,
    TableExpectationType,
    Unique,
    UniqueCombination,
    WithinDays,
)
from moncpipelib.contracts.exceptions import (
    ContractNotFoundError,
    ContractValidationError,
    ContractViolationError,
)
from moncpipelib.contracts.loader import (
    load_all_contracts,
    load_contract,
    load_contract_for_asset,
    load_data_source,
    load_ingest_contract,
    validate_contract_schema,
    validate_ingest_contract_schema,
)
from moncpipelib.contracts.models import (
    SLA,
    CheckResultRow,
    Column,
    ColumnTest,
    ColumnType,
    ContractCorpus,
    ContractEnforcementMode,
    ContractValidationSummary,
    DataContract,
    DataSource,
    FromIngestTemplate,
    IngestContract,
    LineageConfig,
    Owner,
    Period,
    Schema,
    Severity,
    TableExpectation,
    TableReference,
    TestingConfig,
    UpstreamDependency,
    ValidationResult,
)
from moncpipelib.contracts.validators import (
    run_column_test,
    run_post_write_expectations,
    run_table_expectation,
    validate_accepted_values,
    validate_between,
    validate_freshness,
    validate_greater_than,
    validate_greater_than_or_equal,
    validate_less_than,
    validate_less_than_or_equal,
    validate_max_length,
    validate_min_length,
    validate_not_in,
    validate_not_in_future,
    validate_not_null,
    validate_null_percentage,
    validate_pattern,
    validate_row_count,
    validate_row_count_raw,
    validate_schema,
    validate_unique,
    validate_unique_combination,
    validate_within_days,
)

__all__ = [
    # Models
    "CheckResultRow",
    "Column",
    "ColumnTest",
    "ColumnType",
    "ContractCorpus",
    "ContractEnforcementMode",
    "ContractValidationSummary",
    "DataContract",
    "DataSource",
    "FromIngestTemplate",
    "IngestContract",
    "Owner",
    "Period",
    "Schema",
    "Severity",
    "SLA",
    "TableExpectation",
    "TableReference",
    "LineageConfig",
    "TestingConfig",
    "UpstreamDependency",
    "ValidationResult",
    # Exceptions
    "ContractNotFoundError",
    "ContractValidationError",
    "ContractViolationError",
    # Loader functions
    "load_all_contracts",
    "load_contract",
    "load_contract_for_asset",
    "load_data_source",
    "load_ingest_contract",
    "validate_contract_schema",
    "validate_ingest_contract_schema",
    # Validators
    "run_column_test",
    "run_post_write_expectations",
    "run_table_expectation",
    "validate_accepted_values",
    "validate_between",
    "validate_freshness",
    "validate_not_in",
    "validate_greater_than",
    "validate_greater_than_or_equal",
    "validate_less_than",
    "validate_less_than_or_equal",
    "validate_max_length",
    "validate_min_length",
    "validate_not_in_future",
    "validate_not_null",
    "validate_null_percentage",
    "validate_pattern",
    "validate_row_count",
    "validate_row_count_raw",
    "validate_schema",
    "validate_unique",
    "validate_unique_combination",
    "validate_within_days",
    # Asset check generation
    "discover_contract_checks",
    "generate_asset_check",
    "generate_asset_checks_from_contract",
    "load_contract_checks",
    "make_contract_checks",
    # Typed column tests
    "AcceptedValues",
    "Between",
    "GreaterThan",
    "GreaterThanOrEqual",
    "LessThan",
    "LessThanOrEqual",
    "MaxLength",
    "MinLength",
    "NotIn",
    "NotInFuture",
    "NotNull",
    "Pattern",
    "Unique",
    "WithinDays",
    # Typed table expectations
    "Freshness",
    "NullPercentage",
    "RowCount",
    "UniqueCombination",
    # Type aliases
    "ColumnTestType",
    "TableExpectationType",
]
