#!/usr/bin/env python3
"""Generate docs/cookbook.md from cookbook test artifacts.

Reads the JSON artifact file produced by ``pytest --cookbook-collect`` and
renders a Markdown cookbook with tested, copy-paste-ready code examples
and their captured log output.

Usage:
    uv run pytest tests/cookbook/ --cookbook-collect
    uv run python scripts/generate_cookbook.py

Options:
    --artifact PATH   JSON artifact file (default: .cookbook_artifacts.json)
    --output PATH     Output Markdown file (default: docs/cookbook.md)
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_URL = "https://github.com/model-oncology-public/moncpipelib"


def _slugify(text: str) -> str:
    """Convert a title to a Markdown anchor slug."""
    slug = text.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s]+", "-", slug)
    return slug.strip("-")


def _render_toc(groups: dict[str, list[dict[str, Any]]]) -> str:
    """Render a table of contents from grouped artifacts."""
    lines: list[str] = []
    for category, artifacts in groups.items():
        category_title = category.replace("_", " ").title()
        lines.append(f"- [{category_title}](#{_slugify(category_title)})")
        for artifact in artifacts:
            title = artifact["title"]
            lines.append(f"  - [{title}](#{_slugify(title)})")
    return "\n".join(lines)


def _render_artifact(artifact: dict[str, Any]) -> str:
    """Render a single cookbook artifact as a Markdown section."""
    title = artifact["title"]
    description = artifact["description"]
    example_code = artifact["example_code"].rstrip("\n")
    log_output = artifact["log_output"]
    source_file = artifact["source_file"]
    source_line = artifact["source_line"]

    # Convert rst-style inline code to markdown
    description = re.sub(r"``([^`]+)``", r"`\1`", description)

    parts: list[str] = []
    parts.append(f"### {title}\n")
    parts.append(f"{description}\n")
    parts.append(f"```python\n{example_code}\n```\n")

    if log_output.strip():
        parts.append("<details>")
        parts.append("<summary>Output</summary>\n")
        parts.append(f"```\n{log_output.strip()}\n```\n")
        parts.append("</details>\n")

    source_link = f"{REPO_URL}/blob/main/{source_file}#L{source_line}"
    parts.append(f"> Source: [{source_file}:{source_line}]({source_link})\n")

    return "\n".join(parts)


def _render_cookbook(data: dict[str, Any]) -> str:
    """Render the full cookbook.md content from artifact data."""
    artifacts = [a for a in data["artifacts"] if a["passed"]]

    if not artifacts:
        print("WARNING: No passing cookbook tests found.", file=sys.stderr)
        return ""

    # Warn about failures
    failed = [a for a in data["artifacts"] if not a["passed"]]
    for f in failed:
        print(f"WARNING: Skipping failed cookbook test: {f['test_id']}", file=sys.stderr)

    # Group by category, preserving order
    groups: dict[str, list[dict[str, Any]]] = {}
    for artifact in artifacts:
        cat = artifact["category"]
        if cat not in groups:
            groups[cat] = []
        groups[cat].append(artifact)

    # Build document
    lines: list[str] = []

    lines.append("# Cookbook\n")
    lines.append(
        "> **Auto-generated from tested examples.** Do not edit this file manually.\n"
        "> Re-generate with:\n"
        ">\n"
        "> ```\n"
        "> uv run pytest tests/cookbook/ --cookbook-collect\n"
        "> uv run python scripts/generate_cookbook.py\n"
        "> ```\n"
    )

    # Table of contents
    lines.append("## Table of Contents\n")
    lines.append(_render_toc(groups))
    lines.append("")
    lines.append("---\n")

    # Sections by category
    for category, group_artifacts in groups.items():
        category_title = category.replace("_", " ").title()
        lines.append(f"## {category_title}\n")

        for artifact in group_artifacts:
            lines.append(_render_artifact(artifact))
            lines.append("---\n")

    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate cookbook.md from test artifacts.")
    parser.add_argument(
        "--artifact",
        default=".cookbook_artifacts.json",
        help="Path to the cookbook JSON artifact (default: .cookbook_artifacts.json)",
    )
    parser.add_argument(
        "--output",
        default="docs/cookbook.md",
        help="Output path for the generated Markdown (default: docs/cookbook.md)",
    )
    args = parser.parse_args()

    artifact_path = Path(args.artifact)
    if not artifact_path.exists():
        print(f"ERROR: Artifact file not found: {artifact_path}", file=sys.stderr)
        print(
            "Run 'uv run pytest tests/cookbook/ --cookbook-collect' first.",
            file=sys.stderr,
        )
        return 1

    with open(artifact_path) as f:
        data = json.load(f)

    if not data.get("artifacts"):
        print("ERROR: No artifacts found in the artifact file.", file=sys.stderr)
        return 1

    # Refuse to render source that did not come from the test suite (#392):
    # a decorator wrapper once made source resolution land on the wrapping
    # library's file, inlining vendored code into the cookbook.
    foreign = [
        a
        for a in data["artifacts"]
        if Path(a["source_file"]).is_absolute() or not a["source_file"].startswith("tests/")
    ]
    if foreign:
        for a in foreign:
            print(
                f"ERROR: {a['test_id']} resolved source outside tests/: {a['source_file']}",
                file=sys.stderr,
            )
        return 1

    content = _render_cookbook(data)
    if not content:
        return 1

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)

    passing = sum(1 for a in data["artifacts"] if a["passed"])
    total = len(data["artifacts"])
    print(f"Generated {output_path} ({passing}/{total} examples)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
